global:
  scrape_interval: 15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

scrape_configs:
  # … your existing jobs …

  - job_name: 'fake-cluster-overview'
    metrics_path: 'technical/technical_metrics/cluster_overview_metrics.prom'
    static_configs:
      - targets: ['localhost:8000']
    fallback_scrape_protocol: 'PrometheusText0.0.4'

  - job_name: 'fake-container-insights'
    metrics_path: 'technical/technical_metrics/container_insights_metrics.prom'
    static_configs:
      - targets: ['localhost:8000']
    fallback_scrape_protocol: 'PrometheusText0.0.4'

  - job_name: 'fake-tracing-summary'
    metrics_path: 'technical/technical_metrics/tracing_summary_metrics.prom'
    static_configs:
      - targets: ['localhost:8000']
    fallback_scrape_protocol: 'PrometheusText0.0.4'

  - job_name: 'fake-k8s-scheduler'
    metrics_path: 'technical/technical_metrics/k8s_scheduler_health_metrics.prom'
    static_configs:
      - targets: ['localhost:8000']
    fallback_scrape_protocol: 'PrometheusText0.0.4'

  - job_name: 'fake-control-plane'
    metrics_path: 'technical/technical_metrics/control_plane_health_metrics.prom'
    static_configs:
      - targets: ['localhost:8000']
    fallback_scrape_protocol: 'PrometheusText0.0.4'

  - job_name: 'fake-external-api'
    metrics_path: 'technical/technical_metrics/external_api_metrics.prom'
    static_configs:
      - targets: ['localhost:8000']
    fallback_scrape_protocol: 'PrometheusText0.0.4'

#Business Metrics
  - job_name: 'fake-clv-overview'
    metrics_path: 'business/business_metrics/clv_overview_bitblock_metrics.prom'
    static_configs:
      - targets: ['localhost:8000']
    fallback_scrape_protocol: 'PrometheusText0.0.4'

  - job_name: 'fake-conversion-rate'
    metrics_path: 'business/business_metrics/conversion_rate_metrics.prom'
    static_configs:
      - targets: ['localhost:8000']
    fallback_scrape_protocol: 'PrometheusText0.0.4'

  - job_name: 'fake-cost-billing'
    metrics_path: 'business/business_metrics/cost_billing_metrics.prom'
    static_configs:
      - targets: ['localhost:8000']
    fallback_scrape_protocol: 'PrometheusText0.0.4'

  - job_name: 'fake-edu-content'
    metrics_path: 'business/business_metrics/edu_content_bitblock_metrics.prom'
    static_configs:
      - targets: ['localhost:8000']
    fallback_scrape_protocol: 'PrometheusText0.0.4'

  - job_name: 'fake-/market-perf-local'
    metrics_path: 'business/business_metrics/market_perf_local_metrics.prom'
    static_configs:
      - targets: ['localhost:8000']
    fallback_scrape_protocol: 'PrometheusText0.0.4'

  - job_name: 'fake-revenue-per-user'
    metrics_path: 'business/business_metrics/revenue_per_user_metrics.prom'
    static_configs:
      - targets: ['localhost:8000']
    fallback_scrape_protocol: 'PrometheusText0.0.4'

  - job_name: 'fake-seven-day-retention-health'
    metrics_path: 'business/business_metrics/seven_day_retention_rate_metrics.prom'
    static_configs:
      - targets: ['localhost:8000']
    fallback_scrape_protocol: 'PrometheusText0.0.4'

  - job_name: 'fake-user-journey'
    metrics_path: 'business/business_metrics/user_journey_metrics.prom'
    static_configs:
      - targets: ['localhost:8000']
    fallback_scrape_protocol: 'PrometheusText0.0.4'