name: 🤖 Auto Merge PRs

on:
  pull_request:
    types: [labeled]

jobs:
  automerge:
    if: contains(github.event.pull_request.labels.*.name, 'automerge')
    runs-on: ubuntu-latest

    steps:
    - name: 🤖 Auto-merge PR
      uses: pascalgn/automerge-action@v0.15.6
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        MERGE_METHOD: squash
        MERGE_LABELS: "automerge"
