name: 📦 Create GitHub Release

on:
  push:
    branches:
      - main
    paths:
      - 'CHANGELOG.md'
      - '**/*.ts'
      - '**/*.js'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: 📥 Checkout code
      uses: actions/checkout@v4

    - name: 🔧 Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: 🔢 Bump version & generate changelog
      run: |
        npm version patch -m "🚀 release v%s"
        git push --follow-tags

    - name: 📦 Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ github.ref_name }}
        name: Release ${{ github.ref_name }}
