stages:
  - build
  - push

variables:
  IMAGE_TAG: $ECR_REPO:$CI_COMMIT_SHORT_SHA

build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker build -t $IMAGE_TAG .

push:
  stage: push
  script:
    - aws ecr get-login-password | docker login --username AWS --password-stdin $ECR_REGISTRY
    - docker push $IMAGE_TAG
